# Generated by Django 3.2 on 2023-02-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of course')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('cost', models.PositiveIntegerField(verbose_name='cost')),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Hours')),
                ('lessons_num', models.PositiveSmallIntegerField(verbose_name='Hours')),
                ('tasks', models.PositiveSmallIntegerField(verbose_name='Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Head')),
                ('anons', models.CharField(max_length=255, verbose_name='Anons')),
                ('content', models.TextField(blank=True, null=True, verbose_name='News full text')),
                ('content_markdown', models.BooleanField(default=False, verbose_name='As markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Name')),
                ('name', models.CharField(max_length=255, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='mainapp.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Name of course')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('num', models.PositiveSmallIntegerField(verbose_name='Number of lesson')),
                ('tasks', models.PositiveSmallIntegerField(verbose_name='Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses')),
            ],
        ),
    ]
