# Generated by Django 3.2 on 2023-02-22 12:10

from django.db import migrations
from random import randrange




def creation_lessons (apps,se):
    Courses=apps.get_model('mainapp','Courses')
    Lessons = apps.get_model("mainapp", "Lessons")
    for i in Courses.objects.all():
        ln=i.lessons_num
        for j in range(ln):
            Lessons.objects.create(
                title=f"{i.title} - Lesson {j+1}",
                description=f'Курс {i.title}: Описание урока {j+1}',
                num=j+1,
                tasks=randrange(1,15),
                course=i
            )

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_Courses1'),
    ]

    operations = [migrations.RunPython(creation_lessons)]
