# Generated by Django 3.2 on 2023-02-22 12:14

from django.db import migrations
from random import randrange, choice



def creation_teachers (apps,se):
    Courses=apps.get_model('mainapp','Courses')
    Teachers = apps.get_model("mainapp", "Teachers")
    with open('/home/galka/Desktop/DjangoBasics/BraniacLMS/mainapp/documents/teachers', encoding="utf-8") as f:
        a=f.readline()
        while a:
            srnm, nm, ml =a.split()
            item=Teachers.objects.create(
                surname=srnm,
                name=nm,
                email=ml,
                phone=randrange(10000000000,100000000000),
            )
            for i in range(randrange(1,4)):
                item.course.add(choice(Courses.objects.all()))
            a=f.readline()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_Lessons1'),
    ]

    operations = [migrations.RunPython(creation_teachers)
    ]
